spring.application.name=parques-service
server.port=8085
lobby.service.url=${LOBBY_SERVICE_URL:http://azar-alb-774975018.us-east-1.elb.amazonaws.com}
internal.api.key=${INTERNAL_API_KEY:}

parques.rabbitmq.relay-host=${RABBITMQ_STOMP_HOST:localhost}
parques.rabbitmq.relay-port=${RABBITMQ_STOMP_PORT:61613}
parques.rabbitmq.client-login=${RABBITMQ_STOMP_CLIENT_LOGIN:guest}
parques.rabbitmq.client-passcode=${RABBITMQ_STOMP_CLIENT_PASSCODE:guest}
parques.rabbitmq.system-login=${RABBITMQ_STOMP_SYSTEM_LOGIN:guest}
parques.rabbitmq.system-passcode=${RABBITMQ_STOMP_SYSTEM_PASSCODE:guest}
parques.rabbitmq.virtual-host=${RABBITMQ_STOMP_VHOST:/}
parques.rabbitmq.auto-startup=${PARQUES_RABBITMQ_AUTO_STARTUP:true}